
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int P_CLOSE = 14;
  public static final int P_OPEN = 13;
  public static final int IMG_OPEN_WIDTH_100 = 16;
  public static final int DIV_OPEN_WITH_ALIGN = 11;
  public static final int DIV_CLOSE = 12;
  public static final int DOCTYPE_DECLARATION = 2;
  public static final int HEAD_CLOSE = 6;
  public static final int IMG_OPEN_ALIGN_MIDDLE = 15;
  public static final int HTML_OPEN_WITH_LANG = 3;
  public static final int EOF = 0;
  public static final int BODY_OPEN = 9;
  public static final int HTML_CLOSE = 4;
  public static final int ERROR = 1;
  public static final int TITLE_OPEN = 7;
  public static final int TEXT_CONTENT = 17;
  public static final int TITLE_CLOSE = 8;
  public static final int BODY_CLOSE = 10;
  public static final int HEAD_OPEN = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOCTYPE_DECLARATION",
  "HTML_OPEN_WITH_LANG",
  "HTML_CLOSE",
  "HEAD_OPEN",
  "HEAD_CLOSE",
  "TITLE_OPEN",
  "TITLE_CLOSE",
  "BODY_OPEN",
  "BODY_CLOSE",
  "DIV_OPEN_WITH_ALIGN",
  "DIV_CLOSE",
  "P_OPEN",
  "P_CLOSE",
  "IMG_OPEN_ALIGN_MIDDLE",
  "IMG_OPEN_WIDTH_100",
  "TEXT_CONTENT"
  };
}

